package:
  name: username-length-detect
  version: "0.1.0"

source:
  path: source

build:
  number: 0
  script:
    - if: linux
      then: export RUSTFLAGS="${RUSTFLAGS:-} -C target-feature=+crt-static -C relocation-model=static"
    - if: win
      then: set "RUSTFLAGS=%RUSTFLAGS% -C target-feature=+crt-static"
    - if: win
      then: cargo install --locked --force --no-track --root "%PREFIX%" --path .
      else: cargo install --locked --force --no-track --root "${PREFIX}" --path .

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  ignore_run_exports:
    # Linux and Windows binaries statically link the compiler runtime.
    by_name:
      - libgcc
      - vc14_runtime
      - vs2015_runtime
      - ucrt
